server:
  host: localhost
  port: 8000
  persistence:
    type: mongo
    database: spacemoon
    url: mongodb://localhost:27017
    # type: postgres
    # url: host=localhost user=admin password=admin dbname=spacemoon port=5432 sslmode=disable
    # database: spacemoon
  security:
    oauth:
      realm: spacemoon
      clientId: spacemoon-backend
      url: http://localhost:8080/auth
      adminCredentials:
        username: admin
        password: admin
        realm: master
    cors:
      allow-origins:
        - "*"
      allow-methods:
        - "*"
      allow-headers:
        - "*"
      expose-headers:
        - "*"
  payment:
    paypal:
      url: https://api-m.sandbox.paypal.com
      clientId: AfkQVKeSRVJUL5gpbLnM9QAGuRW4NI1Jj-SOemqayU6EvFR6QLAnBh6wULlf9q-XCf9kdr1az17m8aWX
      clientSecret: EAOQbx9-jauX8nGUXiHeD10ypBU3Qnasd5lEeuchw_u7z-3hNvnfdF6JPJWe4npuG1lva3FNAyyu2P6f
    stripe:
      publicKey: pk_test_51M9BVsCmylKw2kXGBy0OzXSYRsRbFL5nbbMKJJ4FOnBXlmc3Kz9GvJW2jPgSnIsSMLqJ4bLxjwNFQuORbZgtG22w00WaZmVePV
      apiKey: sk_test_51M9BVsCmylKw2kXGQK8OUy00lH29NhK8cfWusn2w6Xqf4rXWqbl8xgrPWgZ8Y7DkTlqvlFOEY54WT5wFYnGlACOj00qaVT1w3x
      cancelUrl: "http://localhost:3000/stripe-cancel"
      successUrl: "http://localhost:3000/stripe-success"
